### ISSUE TITLE
Boost Requirement Update

### ISSUE THREAD

**Issue by AshleighRyan** [faodel/faodel#1]
On the install page, the required Boost version is listed as 1.60 or higher, but 1.67 or higher is actually required.

**Comment by tkordenbrock** [comment]
@AshleighRyan reports that the cmake/FaodelTPLs.cmake in her clone required Boost 1.67.0 or later even though the repo still has Boost 1.60.0 or later.  Unfortunately, the machine had to be wiped so there is no way to know how that happened.  I'm closing this ticket, but @AshleighRyan can reopen if the problem returns.
