### ISSUE TITLE
HIP/CUDA Support

### ISSUE THREAD

**Issue by kwryankrattiger** [faodel/faodel#10]
Is there a plan to add interop with HIP/CUDA to faodel to directly send/recieve data from/to GPUs?

**Comment by craigulmer** [comment]
We don't have plans for GPU memory at the moment. If you have a need or ideas on how it should work, we'd be interested in hearing more.

Supporting GPU memory comes up periodically, but we haven't had a strong driver for integrating it into faodel's memory management services. Usually people on our side of things are using Kokkos plus a cuda-aware MPI to ship data around within an application, and then Kelpie to share objects with external MPI applications.  One of the challenges to dealing with memory is that cuda and ib need to work together properly, so one doesn't deregister/unpin an allocation before the other needs it. We probably would need to change out our lunasa allocator to make this work properly. Would be interesting, but we've got a few other priorities at the moment.

**Comment by kwryankrattiger** [comment]
Awesome. I don't have any recommendations on the how, but Kokkos is used pretty heavily by many of the projects that we have been working with and it seems to be filling the needs well for now. Thanks!
