### ISSUE TITLE
Cannot compile FAODEL when disabling MPI

### ISSUE THREAD

**Issue by fbudin69500** [faodel/faodel#4]
When trying to compile FAODEL with `Faodel_ENABLE_MPI_SUPPORT` set to OFF, I get the following error message:

[ 80%] Building CXX object src/kelpie/CMakeFiles/kelpie.dir/services/PoolServerDriver.cpp.o
/home/francois.budin/devel/adios/playground/faodel/src/kelpie/services/PoolServerDriver.cpp:11:10: fatal error: mpi.h: No such file or directory
 #include <mpi.h>
          ^~~~~~~
compilation terminated.

**Comment by craigulmer** [comment]
Thanks- @pwidene can you verify this fix?

**Comment by pwidene** [comment]
I was having a debate with myself over whether the check for Faodel_ENABLE_MPI_SUPPORT should be done in a higher CMakeLists in order to avoid the call downward entirely, but I suppose we might eventually come up with a kelpie server process that doesn't rely on MPI. So, LGTM.

**Comment by tkordenbrock** [comment]
Closed by #3.
