### ISSUE TITLE
Cannot compile FAODEL with `Faodel_LOGGING_METHOD` set to `sbl`

### ISSUE THREAD

**Issue by fbudin69500** [faodel/faodel#5]
When trying to compile FAODEL with  `Faodel_LOGGING_METHOD` set to `sbl`, I get the following error message:

Scanning dependencies of target common
[ 27%] Building CXX object src/faodel-common/CMakeFiles/common.dir/LoggingInterface.cpp.o
/home/francois.budin/devel/adios/playground/faodel/src/faodel-common/LoggingInterface.cpp:14:10: fatal error: sbl/sbl_logger.hpp: No such file or directory
 #include <sbl/sbl_logger.hpp>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by craigulmer** [comment]
Thanks- I think we had a patch for this in our upstream repo that didn't make it out. @tkordenbrock can you verify this is consistent with the fix we made there. Looks fine to me.

**Comment by tkordenbrock** [comment]
Closed by #2.
